// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE( 64, GGML_TYPE_PQ3_5, GGML_TYPE_F16);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_PQ3_5, GGML_TYPE_F16);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_PQ3_5, GGML_TYPE_F16);
